# Generated by Django 4.0.1 on 2022-01-27 12:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_cs",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Titulek"
                    ),
                ),
                (
                    "title_eng",
                    models.CharField(max_length=100, unique=True, verbose_name="Title"),
                ),
                ("content_cs", ckeditor.fields.RichTextField()),
                ("content_eng", ckeditor.fields.RichTextField()),
                ("header_image", models.ImageField(upload_to="images/header_image")),
                ("thumb_image", models.ImageField(upload_to="images/thumb_image")),
                ("tags", models.ManyToManyField(to="blog.Tag")),
            ],
        ),
    ]
