# Generated by Django 4.0.1 on 2022-01-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="header_image",
            field=models.ImageField(upload_to="media/images/header_image"),
        ),
        migrations.AlterField(
            model_name="article",
            name="thumb_image",
            field=models.ImageField(upload_to="media/images/thumb_image"),
        ),
    ]
