# Generated by Django 4.0.1 on 2022-01-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_header_image_alter_article_thumb_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(to="blog.Tag", verbose_name="Tags"),
        ),
    ]
